# Generated by Django 5.1.5 on 2025-01-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add or Remove Warehouse',
            },
        ),
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='product-images/')),
                ('product_price', models.CharField(max_length=10)),
                ('product_description', models.TextField(max_length=1000)),
                ('warehouse_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='zaher_app_warehouse.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Stock Management',
            },
        ),
    ]
