# Generated by Django 5.1.5 on 2025-01-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaher_app', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
