# Generated by Django 5.1.5 on 2025-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaher_app', '0004_contactinfo_closing_day_contactinfo_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
