# Generated by Django 5.1.5 on 2025-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaher_app', '0005_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
