# Generated by Django 5.1.5 on 2025-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaher_app', '0006_aboutus_company_name_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='company_locations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
